version: "3.8"

services:
  prisma-nest-postgres-db:
    container_name: fullstack_todo_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: fullstack-app-prisma-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
